Repository blackjax-devs/blackjax, pull requests merged in 2022-09, with the labels that each got.

#272 Add Aeppl/Aesara example
  examples/aesara.md
  examples/numpyro.md
  examples/pymc.md
  examples/tfp.md
Labels: documentation

#229 Add the Generalized HMC sampler + ECA adaptation (MEADS)
  blackjax/__init__.py
  blackjax/adaptation/__init__.py
  blackjax/adaptation/chain_adaptation.py
  blackjax/adaptation/meads.py
  blackjax/kernels.py
  blackjax/mcmc/__init__.py
  blackjax/mcmc/ghmc.py
  blackjax/mcmc/hmc.py
  blackjax/mcmc/proposal.py
  blackjax/mcmc/trajectory.py
  docs/adaptation.rst
  docs/examples.rst
  docs/sampling.rst
  examples/GP_EllipticalSliceSampler.md
  examples/PeriodicOrbitalMCMC.md
  examples/RegimeSwitchingModel.md
  examples/SparseLogisticRegression.md
  tests/test_sampling.py
Labels: enhancement, sampler

#293 Allow users to pass a float for constant learning rate
  blackjax/kernels.py
  examples/SGMCMC.md
  tests/test_sampling.py
Labels: enhancement

#277 Example clean up
  docs/conf.py
  docs/howtos.rst
  docs/index.rst
  examples/PeriodicOrbitalMCMC.md
  examples/README.md
  examples/RegimeSwitchingModel.md
  examples/SparseLogisticRegression.md
  examples/aesara.md
  examples/change_of_variable_hmc.md
  examples/numpyro.md
  examples/pymc.md
  examples/tfp.md
  requirements-doc.txt
Labels: documentation
